### ISSUE TITLE
# TODO: Reviewer fix list

### ISSUE THREAD

**Issue by MenasheKoren** [MenasheKoren/news-explorer-api#17]
# TODO: Reviewer fix list

### Performance Criteria

- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  ###default port should be 3000 instead of 8000
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
  ###default port should be 3000 instead of 8000
- [x]  The following routes function as described:
	- [x] `GET /articles` returns all articles saved by the user.
	###https://snipboard.io/5O3V0p.jpg The server should return an empty array if no articles are found
	- [x] `POST /signup` creates a user with the data passed inside the request body.
	###https://snipboard.io/o1nYxS.jpg When creating a user with an email that already exists in the database, you must return an error with the status code 409 (Conflict) instead of 500. You can catch the error by using err.name = MongoError and err.code = 11000.
	
- [x]  In production mode, the database address is taken from `process.env`.
###https://snipboard.io/seTODk.jpg

- [x]  Users can't delete saved cards from other user profiles.
###https://snipboard.io/4HBjN3.jpg When the user tries to delete someone else's card, an error with a 403 status should be returned. If you've forgotten something, or have some doubts, you can check this reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
- [x]  The server can be accessed via HTTPS using the domain specified in README.md. 
###https://api.news-explorer.mk.students.nomoreparties.sbs/ SSL certificate issue

### Best Practices

- [x]  The server can be accessed via HTTPS using the domain specified in `README.md`. 
###https://api.news-explorer.mk.students.nomoreparties.sbs/ SSL certificate issue

### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
https://snipboard.io/H7Kv8m.jpg In places where errors may occur, instead of returning them, let the middleware handle them. To review the rules of centralized error handling, refer to the corresponding lesson (https://practicum.yandex.com/learn/web/courses/a85a6154-c7a2-45be-8995-f596192e0306/sprints/4224/topics/01ee90cb-bb28-42dd-bcfe-5f2b06ce30b9/lessons/2d9ba54f-8065-45ff-916b-b835db81d42f/ ). Also, this article might be helpful https://dev.to/nedsoft/central-error-handling-in-express-3aej 
- [x]  Configuration and constants are stored in separate files:
	- [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
	###https://snipboard.io/seTODk.jpg
	
- [x]  The API is hosted on a separate subdomain, e.g. api.news-explorer.tk.
